name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Сделаем папку безопасной для git
            git config --global --add safe.directory /home/root/bot-project

            # Переходим в папку с проектом
            cd /home/root/bot-project

            # Подгружаем NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22.18.0

            # Устанавливаем зависимости (production)
            npm ci --production

            # Перезапускаем PM2
            pm2 reload tigran-food-bot || pm2 start bot.js --name tigran-food-bot
