name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/root/bot-project
            git config --global --add safe.directory /home/root/bot-project

            # Обновляем код
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            # Загружаем Node через NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22.18.0

            # Экспортируем .env переменные для Node
            export $(grep -v '^#' .env | xargs)

            # Устанавливаем зависимости
            npm ci --production

            # Полностью перезапускаем PM2
            pm2 delete tigranFoodBot || true
            pm2 start bot.js --name tigranFoodBot
            pm2 save
