name: Deploy TigranFoodBot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Переходим в папку проекта
            cd /home/root/bot-project

            # Устанавливаем зависимости (production)
            /root/.nvm/versions/node/v22.18.0/bin/npm ci --production

            # Перезапускаем бота, если нет — стартуем
            /root/.nvm/versions/node/v22.18.0/bin/pm2 reload TigranFoodBot || \
            /root/.nvm/versions/node/v22.18.0/bin/pm2 start bot.js --name TigranFoodBot

            # Сохраняем PM2 конфигурацию, чтобы автозапуск был после перезагрузки сервера
            /root/.nvm/versions/node/v22.18.0/bin/pm2 save
